---
language: python
python:
  - "2.7"
  - "3.6"
sudo: required
install:
  - pip install ansible
  - ansible --version
  - printf '[defaults]\nroles_path=../' > ansible.cfg
script:
  - ansible-playbook -D -i tests/inventory tests/test.yml
notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
...
