---
- name: Include operating system specific variables
  tags: ntp
  include_vars:
    file: "{{ ansible_os_family }}.yml"

- name: Ensure that the ntp package is installed
  tags: ntp
  become: true
  package:
    name: "{{ ntp_package_name }}"
    state: present

- name: Attempting to overlay ntp configurations
  tags: ntp
  become: true
  template:
    src: "{{ item.template }}"
    dest: "{{ item.path }}"
    owner: root
    group: root
    mode: 0644
  notify: restart ntpd
  with_items: "{{ ntp_configs }}"

- name: Ensure that ntpd is started and enabled on boot
  tags: ntp
  become: true
  service:
    enabled: yes
    name: "{{ ntp_service_name }}"
    state: started
...
