---
- name: Ensure that the ntp package is installed
  tags: ntp
  become: true
  yum:
    name: ntp
    state: present

- name: Attempting to overlay ntp configurations
  tags: ntp
  become: true
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dst }}"
    owner: root
    group: root
    mode: 0644
  notify: restart ntpd
  with_items:
    - { src: ntp.conf.j2, dst: /etc/ntp.conf }
    - { src: ntpd.sysconfig.j2, dst: /etc/sysconfig/ntpd }

- name: Ensure that ntpd is started and enabled on boot
  tags: ntp
  become: true
  service:
    enabled: yes
    name: ntpd
    state: started
...
